#pragma once

#include <mc/dsp/wavelet/filters/coif.hpp>
#include <mc/dsp/wavelet/filters/daubechies.hpp>
#include <mc/dsp/wavelet/filters/sym.hpp>
#include <mc/dsp/wavelet/wavelet_coefficients.hpp>

namespace mc::dsp {
template<typename T>
inline constexpr auto daubechiesWavelets = Array<WaveletCoefficients<T>, 38>{
    WaveletCoefficients<T>{ "db1",  daubechies1<T>,  2},
    WaveletCoefficients<T>{ "db2",  daubechies2<T>,  4},
    WaveletCoefficients<T>{ "db3",  daubechies3<T>,  6},
    WaveletCoefficients<T>{ "db4",  daubechies4<T>,  8},
    WaveletCoefficients<T>{ "db5",  daubechies5<T>, 10},
    WaveletCoefficients<T>{ "db6",  daubechies6<T>, 12},
    WaveletCoefficients<T>{ "db7",  daubechies7<T>, 14},
    WaveletCoefficients<T>{ "db8",  daubechies8<T>, 16},
    WaveletCoefficients<T>{ "db9",  daubechies9<T>, 18},
    WaveletCoefficients<T>{"db10", daubechies10<T>, 20},
    WaveletCoefficients<T>{"db11", daubechies11<T>, 22},
    WaveletCoefficients<T>{"db12", daubechies12<T>, 24},
    WaveletCoefficients<T>{"db13", daubechies13<T>, 26},
    WaveletCoefficients<T>{"db14", daubechies14<T>, 28},
    WaveletCoefficients<T>{"db15", daubechies15<T>, 30},
    WaveletCoefficients<T>{"db16", daubechies16<T>, 32},
    WaveletCoefficients<T>{"db17", daubechies17<T>, 34},
    WaveletCoefficients<T>{"db18", daubechies18<T>, 36},
    WaveletCoefficients<T>{"db19", daubechies19<T>, 38},
    WaveletCoefficients<T>{"db20", daubechies20<T>, 40},
    WaveletCoefficients<T>{"db21", daubechies21<T>, 42},
    WaveletCoefficients<T>{"db22", daubechies22<T>, 44},
    WaveletCoefficients<T>{"db23", daubechies23<T>, 46},
    WaveletCoefficients<T>{"db24", daubechies24<T>, 48},
    WaveletCoefficients<T>{"db25", daubechies25<T>, 50},
    WaveletCoefficients<T>{"db26", daubechies26<T>, 52},
    WaveletCoefficients<T>{"db27", daubechies27<T>, 54},
    WaveletCoefficients<T>{"db28", daubechies28<T>, 56},
    WaveletCoefficients<T>{"db29", daubechies29<T>, 58},
    WaveletCoefficients<T>{"db30", daubechies30<T>, 60},
    WaveletCoefficients<T>{"db31", daubechies31<T>, 62},
    WaveletCoefficients<T>{"db32", daubechies32<T>, 64},
    WaveletCoefficients<T>{"db33", daubechies33<T>, 66},
    WaveletCoefficients<T>{"db34", daubechies34<T>, 68},
    WaveletCoefficients<T>{"db35", daubechies35<T>, 70},
    WaveletCoefficients<T>{"db36", daubechies36<T>, 72},
    WaveletCoefficients<T>{"db37", daubechies37<T>, 74},
    WaveletCoefficients<T>{"db38", daubechies38<T>, 76},
};

template<typename T>
inline constexpr auto symWavelets = Array<WaveletCoefficients<T>, 19>{
    WaveletCoefficients<T>{ "sym2",  sym2<T>,  4},
    WaveletCoefficients<T>{ "sym3",  sym3<T>,  6},
    WaveletCoefficients<T>{ "sym4",  sym4<T>,  8},
    WaveletCoefficients<T>{ "sym5",  sym5<T>, 10},
    WaveletCoefficients<T>{ "sym6",  sym6<T>, 12},
    WaveletCoefficients<T>{ "sym7",  sym7<T>, 14},
    WaveletCoefficients<T>{ "sym8",  sym8<T>, 16},
    WaveletCoefficients<T>{ "sym9",  sym9<T>, 18},
    WaveletCoefficients<T>{"sym10", sym10<T>, 20},
    WaveletCoefficients<T>{"sym11", sym11<T>, 22},
    WaveletCoefficients<T>{"sym12", sym12<T>, 24},
    WaveletCoefficients<T>{"sym13", sym13<T>, 26},
    WaveletCoefficients<T>{"sym14", sym14<T>, 28},
    WaveletCoefficients<T>{"sym15", sym15<T>, 30},
    WaveletCoefficients<T>{"sym16", sym16<T>, 32},
    WaveletCoefficients<T>{"sym17", sym17<T>, 34},
    WaveletCoefficients<T>{"sym18", sym18<T>, 36},
    WaveletCoefficients<T>{"sym19", sym19<T>, 38},
    WaveletCoefficients<T>{"sym20", sym20<T>, 40},
};

template<typename T>
inline constexpr auto coifWavelets = Array<WaveletCoefficients<T>, 17>{
    WaveletCoefficients<T>{ "coif1",  coif1<T>,   6},
    WaveletCoefficients<T>{ "coif2",  coif2<T>,  12},
    WaveletCoefficients<T>{ "coif3",  coif3<T>,  18},
    WaveletCoefficients<T>{ "coif4",  coif4<T>,  24},
    WaveletCoefficients<T>{ "coif5",  coif5<T>,  30},
    WaveletCoefficients<T>{ "coif6",  coif6<T>,  36},
    WaveletCoefficients<T>{ "coif7",  coif7<T>,  42},
    WaveletCoefficients<T>{ "coif8",  coif8<T>,  48},
    WaveletCoefficients<T>{ "coif9",  coif9<T>,  54},
    WaveletCoefficients<T>{"coif10", coif10<T>,  60},
    WaveletCoefficients<T>{"coif11", coif11<T>,  66},
    WaveletCoefficients<T>{"coif12", coif12<T>,  72},
    WaveletCoefficients<T>{"coif13", coif13<T>,  78},
    WaveletCoefficients<T>{"coif14", coif14<T>,  84},
    WaveletCoefficients<T>{"coif15", coif15<T>,  90},
    WaveletCoefficients<T>{"coif16", coif16<T>,  96},
    WaveletCoefficients<T>{"coif17", coif17<T>, 102},
};

template<typename T>
inline constexpr auto allWavelets = Array<WaveletCoefficients<T>, 38 + 19 + 17>{
    WaveletCoefficients<T>{   "db1",  Span<T const>{daubechies1<T>},   2},
    WaveletCoefficients<T>{   "db2",  Span<T const>{daubechies2<T>},   4},
    WaveletCoefficients<T>{   "db3",  Span<T const>{daubechies3<T>},   6},
    WaveletCoefficients<T>{   "db4",  Span<T const>{daubechies4<T>},   8},
    WaveletCoefficients<T>{   "db5",  Span<T const>{daubechies5<T>},  10},
    WaveletCoefficients<T>{   "db6",  Span<T const>{daubechies6<T>},  12},
    WaveletCoefficients<T>{   "db7",  Span<T const>{daubechies7<T>},  14},
    WaveletCoefficients<T>{   "db8",  Span<T const>{daubechies8<T>},  16},
    WaveletCoefficients<T>{   "db9",  Span<T const>{daubechies9<T>},  18},
    WaveletCoefficients<T>{  "db10", Span<T const>{daubechies10<T>},  20},
    WaveletCoefficients<T>{  "db11", Span<T const>{daubechies11<T>},  22},
    WaveletCoefficients<T>{  "db12", Span<T const>{daubechies12<T>},  24},
    WaveletCoefficients<T>{  "db13", Span<T const>{daubechies13<T>},  26},
    WaveletCoefficients<T>{  "db14", Span<T const>{daubechies14<T>},  28},
    WaveletCoefficients<T>{  "db15", Span<T const>{daubechies15<T>},  30},
    WaveletCoefficients<T>{  "db16", Span<T const>{daubechies16<T>},  32},
    WaveletCoefficients<T>{  "db17", Span<T const>{daubechies17<T>},  34},
    WaveletCoefficients<T>{  "db18", Span<T const>{daubechies18<T>},  36},
    WaveletCoefficients<T>{  "db19", Span<T const>{daubechies19<T>},  38},
    WaveletCoefficients<T>{  "db20", Span<T const>{daubechies20<T>},  40},
    WaveletCoefficients<T>{  "db21", Span<T const>{daubechies21<T>},  42},
    WaveletCoefficients<T>{  "db22", Span<T const>{daubechies22<T>},  44},
    WaveletCoefficients<T>{  "db23", Span<T const>{daubechies23<T>},  46},
    WaveletCoefficients<T>{  "db24", Span<T const>{daubechies24<T>},  48},
    WaveletCoefficients<T>{  "db25", Span<T const>{daubechies25<T>},  50},
    WaveletCoefficients<T>{  "db26", Span<T const>{daubechies26<T>},  52},
    WaveletCoefficients<T>{  "db27", Span<T const>{daubechies27<T>},  54},
    WaveletCoefficients<T>{  "db28", Span<T const>{daubechies28<T>},  56},
    WaveletCoefficients<T>{  "db29", Span<T const>{daubechies29<T>},  58},
    WaveletCoefficients<T>{  "db30", Span<T const>{daubechies30<T>},  60},
    WaveletCoefficients<T>{  "db31", Span<T const>{daubechies31<T>},  62},
    WaveletCoefficients<T>{  "db32", Span<T const>{daubechies32<T>},  64},
    WaveletCoefficients<T>{  "db33", Span<T const>{daubechies33<T>},  66},
    WaveletCoefficients<T>{  "db34", Span<T const>{daubechies34<T>},  68},
    WaveletCoefficients<T>{  "db35", Span<T const>{daubechies35<T>},  70},
    WaveletCoefficients<T>{  "db36", Span<T const>{daubechies36<T>},  72},
    WaveletCoefficients<T>{  "db37", Span<T const>{daubechies37<T>},  74},
    WaveletCoefficients<T>{  "db38", Span<T const>{daubechies38<T>},  76},

    WaveletCoefficients<T>{  "sym2",         Span<T const>{sym2<T>},   4},
    WaveletCoefficients<T>{  "sym3",         Span<T const>{sym3<T>},   6},
    WaveletCoefficients<T>{  "sym4",         Span<T const>{sym4<T>},   8},
    WaveletCoefficients<T>{  "sym5",         Span<T const>{sym5<T>},  10},
    WaveletCoefficients<T>{  "sym6",         Span<T const>{sym6<T>},  12},
    WaveletCoefficients<T>{  "sym7",         Span<T const>{sym7<T>},  14},
    WaveletCoefficients<T>{  "sym8",         Span<T const>{sym8<T>},  16},
    WaveletCoefficients<T>{  "sym9",         Span<T const>{sym9<T>},  18},
    WaveletCoefficients<T>{ "sym10",        Span<T const>{sym10<T>},  20},
    WaveletCoefficients<T>{ "sym11",        Span<T const>{sym11<T>},  22},
    WaveletCoefficients<T>{ "sym12",        Span<T const>{sym12<T>},  24},
    WaveletCoefficients<T>{ "sym13",        Span<T const>{sym13<T>},  26},
    WaveletCoefficients<T>{ "sym14",        Span<T const>{sym14<T>},  28},
    WaveletCoefficients<T>{ "sym15",        Span<T const>{sym15<T>},  30},
    WaveletCoefficients<T>{ "sym16",        Span<T const>{sym16<T>},  32},
    WaveletCoefficients<T>{ "sym17",        Span<T const>{sym17<T>},  34},
    WaveletCoefficients<T>{ "sym18",        Span<T const>{sym18<T>},  36},
    WaveletCoefficients<T>{ "sym19",        Span<T const>{sym19<T>},  38},
    WaveletCoefficients<T>{ "sym20",        Span<T const>{sym20<T>},  40},

    WaveletCoefficients<T>{ "coif1",        Span<T const>{coif1<T>},   6},
    WaveletCoefficients<T>{ "coif2",        Span<T const>{coif2<T>},  12},
    WaveletCoefficients<T>{ "coif3",        Span<T const>{coif3<T>},  18},
    WaveletCoefficients<T>{ "coif4",        Span<T const>{coif4<T>},  24},
    WaveletCoefficients<T>{ "coif5",        Span<T const>{coif5<T>},  30},
    WaveletCoefficients<T>{ "coif6",        Span<T const>{coif6<T>},  36},
    WaveletCoefficients<T>{ "coif7",        Span<T const>{coif7<T>},  42},
    WaveletCoefficients<T>{ "coif8",        Span<T const>{coif8<T>},  48},
    WaveletCoefficients<T>{ "coif9",        Span<T const>{coif9<T>},  54},
    WaveletCoefficients<T>{"coif10",       Span<T const>{coif10<T>},  60},
    WaveletCoefficients<T>{"coif11",       Span<T const>{coif11<T>},  66},
    WaveletCoefficients<T>{"coif12",       Span<T const>{coif12<T>},  72},
    WaveletCoefficients<T>{"coif13",       Span<T const>{coif13<T>},  78},
    WaveletCoefficients<T>{"coif14",       Span<T const>{coif14<T>},  84},
    WaveletCoefficients<T>{"coif15",       Span<T const>{coif15<T>},  90},
    WaveletCoefficients<T>{"coif16",       Span<T const>{coif16<T>},  96},
    WaveletCoefficients<T>{"coif17",       Span<T const>{coif17<T>}, 102},
};

}  // namespace mc::dsp
