name: Linux

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build lcov gcovr

          pip3 install conan
          conan config init
          conan config set general.revisions_enabled=1
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: CMake configure -- Release
        run: cmake -S . -G Ninja -B cmake-build-release -DCMAKE_BUILD_TYPE=Release

      - name: CMake build -- Release
        run: cmake --build cmake-build-release

      - name: CTest -- Release
        run: ctest --test-dir cmake-build-release -C Release
