name: Windows

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Install dependencies
        run: |
          choco install ninja
          pip install conan
          conan config init
          conan config set general.revisions_enabled=1
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake configure -- Release
        run: cmake -S . -B cmake-build-release -G "Ninja" -D CMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=ON

      - name: CMake build -- Release
        run: cmake --build cmake-build-release --config "Release"

      - name: CTest -- Release
        run: ctest --test-dir cmake-build-release -C Release --parallel 2
