name: macOS

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-12
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.14"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Install dependencies
        run: |
          brew update
          brew install ninja conan
          conan config init
          conan config set general.revisions_enabled=1
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: CMake configure -- Release
        run: cmake -S . -G "Ninja" -B cmake-build-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=ON

      - name: CMake build -- Release
        run: cmake --build cmake-build-release

      - name: CTest -- Release
        run: ctest --test-dir cmake-build-release -C Release --parallel 2
